apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-with-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-with-quarkus
  template:
    metadata:
      labels:
        app: code-with-quarkus
    spec:
      imagePullSecrets:
      - name: ecr-regcred
      containers:
      - name: quarkus
        image: 751236674196.dkr.ecr.eu-central-1.amazonaws.com/quarkus-app:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent